# TSP — Segunda instancia (eil51)

**Optimización DS2011 — fase 7.** Repite los experimentos con la
configuración ya calibrada sobre `eil51` (51 ciudades, óptimo conocido 426,
confirmado contra el archivo `solutions` oficial de TSPLIB). Cierra el punto
débil del informe: ya no depende solo de un ejemplo ficticio de 6 nodos.

In [1]:
import sys
from pathlib import Path

RAIZ = Path.cwd()
if not (RAIZ / "src" / "tsp").exists():
    RAIZ = RAIZ.parent
sys.path.insert(0, str(RAIZ / "src"))
import pandas as pd
from tsp.config import leer_config
from tsp.datos import leer_tsp, matriz_distancias, longitud_ruta
from tsp.heuristicas import vecino_mas_cercano, dos_opt

inst = leer_tsp(RAIZ / "data" / "raw" / "eil51.tsp")
D = matriz_distancias(inst.coords)
OPTIMO = 426
config = leer_config(RAIZ / "config" / "best.yaml")

## Demo en vivo: NN + 2-opt sobre eil51 (instantáneo)

In [2]:
ruta = dos_opt(vecino_mas_cercano(D, inicio=0), D)
costo = longitud_ruta(ruta, D)
print(f"NN+2opt en eil51: L={costo}  gap={(costo - OPTIMO) / OPTIMO * 100:.2f}%")

NN+2opt en eil51: L=438  gap=2.82%

## Resultados completos (30 semillas, configuración calibrada en la fase 6)

Ya calculados por `ejecutables/fase7_eil51.py`; se cargan desde el CSV
guardado.

In [3]:
eil51_resumen = pd.read_csv(RAIZ / "results" / "tables" / "eil51_resumen.csv")
eil51_resumen.sort_values("gap_medio_pct")

,algo,mejor,media,desviacion,gap_mejor_pct,gap_medio_pct
4,recocido_simulado,426,430.066667,2.839783,0.00,0.95
3,nearest_neighbor+2opt,438,438.000000,0.000000,2.82,2.82
0,genetico,429,451.066667,9.627308,0.70,5.88
1,hormigas,438,453.366667,5.756456,2.82,6.42
2,nearest_neighbor,511,511.000000,0.000000,19.95,19.95

## Comparación berlin52 vs. eil51

In [4]:
comparacion = pd.read_csv(RAIZ / "results" / "tables" / "comparacion_instancias.csv")
comparacion.sort_values(["instance", "gap_medio_pct"])

,algo,mejor,media,desviacion,gap_mejor_pct,gap_medio_pct,instance
4,recocido_simulado,7542,7550.700000,42.670469,0.00,0.12,berlin52
1,hormigas,7680,7913.133333,73.786146,1.83,4.92,berlin52
3,nearest_neighbor+2opt,7967,7967.000000,0.000000,5.64,5.64,berlin52
0,genetico,7758,8144.800000,237.422713,2.86,7.99,berlin52
2,nearest_neighbor,8980,8980.000000,0.000000,19.07,19.07,berlin52
9,recocido_simulado,426,430.066667,2.839783,0.00,0.95,eil51
8,nearest_neighbor+2opt,438,438.000000,0.000000,2.82,2.82,eil51
5,genetico,429,451.066667,9.627308,0.70,5.88,eil51
6,hormigas,438,453.366667,5.756456,2.82,6.42,eil51
7,nearest_neighbor,511,511.000000,0.000000,19.95,19.95,eil51

El orden entre algoritmos se mantiene igual en las dos instancias: el
recocido simulado es, de nuevo, el método más consistente y el que mejor se
acerca al óptimo.